serverAddr = "49.235.34.253"
serverPort = 7900
auth.method = "token"
auth.token = "123"

[[visitors]]
name = "snk_163vip2"
type = "xtcp"
serverName = "snk_163vip2"
secretKey = "abc123"
bindPort = 53158

[[visitors]]
name = "snk_12901"
type = "xtcp"
serverName = "snk_12901"
secretKey = "abc123"
bindPort = 39254

